### ISSUE TITLE
Razer Ornata V2 not supported

### ISSUE THREAD

**Issue by FIvanO** [openrazer/openrazer#1359] opened 2020-12-01 11:46 UTC
Razer Ornata V2 not supported. Tried on Linux 20.04

**Comment by FIvanO** [comment] 2020-12-01 12:23
openrazer-daemon can't recognize "Razer Ornata V2" keyboard. Does someone have any tips on how to recognize it?
(Screen from razer-genie app)
![image](https://user-images.githubusercontent.com/23000810/100739994-aa6ea180-33e0-11eb-9337-a316530aa82f.png)

Thanks

**Comment by nightsky30** [comment] 2020-12-01 18:35
Support for this device is tracked in #1187

**Comment by FIvanO** [comment] 2020-12-01 18:40
Did not found there at least something useful for resolving the issue.

**Comment by nightsky30** [comment] 2020-12-01 19:07
The linked issue is to track adding support for the Ornata V2. It is not supported by the daemon at this time. There is nothing that can be done regarding your issue other than actually adding and testing the code to support the device.

**Comment by z3ntu** [comment] 2020-12-03 13:19
Closing as duplicate of #1187 , thanks @nightsky30

**Closed as completed by z3ntu** 2020-12-03 13:19 UTC
Labels: duplicate
