### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by 0x77dev** [openrazer/openrazer#1038] opened 2020-03-02 20:27 UTC
### Support

- [ NO NEEDED IN THIS CASE ] Have you tried rebooting?
- [ YES ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

**Comment by redaxmedia** [comment] 2020-03-12 13:38
I suggest to start with extending the `.travis.yml`file and see what happens:

```
os:
 - linux
 - osx
```

**Comment by lah7** [comment] 2020-03-12 13:45
Duplicate of #959, #991, #785, #623 and #515.

Simply put, it's not possible for OpenRazer in its current form to run on Windows/Mac because it depends on a Linux-only driver. There's @z3ntu's [razer_test](https://github.com/z3ntu/razer_test/) which handles everything in user space, eliminating the need for a driver. It's a work-in-progress, and is already making progress to run on Windows/Mac.

Eventually that project will supersede OpenRazer 2.x, so hopefully some day.

**Closed as completed by lah7** 2020-03-12 13:45 UTC
Labels: support
