### ISSUE TITLE
Support for Basilisk X HyperSpeed (bluetooth)

### ISSUE THREAD

**Issue by D33M0N** [openrazer/openrazer#1504] opened 2021-05-01 14:37 UTC
### Device Info

* Name: Basilisk X HyperSpeed
* Product Number: RC30-03150100-0000
* Model Number: RC30-031501

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```
Nope. 0 output for this command. it's BT device, not USB.
```
$ dmesg | grep "1532:"
[141961.614705] input: Basilisk X HyperSpeed Mouse as /devices/virtual/misc/uhid/0005:1532:0082.0009/input/input23
[141961.614789] input: Basilisk X HyperSpeed Consumer Control as /devices/virtual/misc/uhid/0005:1532:0082.0009/input/input24
[141961.614823] input: Basilisk X HyperSpeed System Control as /devices/virtual/misc/uhid/0005:1532:0082.0009/input/input25
[141961.614849] input: Basilisk X HyperSpeed as /devices/virtual/misc/uhid/0005:1532:0082.0009/input/input26
[141961.614879] input: Basilisk X HyperSpeed Keyboard as /devices/virtual/misc/uhid/0005:1532:0082.0009/input/input27
[141961.614916] hid-generic 0005:1532:0082.0009: input,hidraw8: BLUETOOTH HID v0.01 Mouse [Basilisk X HyperSpeed] on f8:e4:e3:00:d2:b8
```

```
Please post the output of
    ls -lah /dev/input/by-id/
```
not there either...
it's /dev/mouse1
but under /dev/input/by-id/ there is no link to mouse1, just for mouse0 (my other wired non-razer mouse).

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>

**Comment by z3ntu** [comment] 2021-05-14 07:12
Duplicate of #1339

**Closed as completed by z3ntu** 2021-05-14 07:12 UTC
Labels: duplicate, Device Support
