### ISSUE TITLE
Support for [Razer Basilisk]

### ISSUE THREAD

**Issue by b0ff3n** [openrazer/openrazer#911] opened 2019-09-12 15:20 UTC
### Device Info

* Name: Razer Basilisk
* Product Number: RZ01-02330100
* Model Number: RZ01-0233

### Device Information
```
Bus 001 Device 008: ID 1532:0064 Razer USA, Ltd 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0064 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1

```

```
totalt 0
drwxr-xr-x 2 root root 420 sep.  12 15:59 .
drwxr-xr-x 4 root root 860 sep.  12 15:59 ..
lrwxrwxrwx 1 root root  10 sep.  12 15:59 usb-Mad_Catz_Saitek_Pro_Flight_X-56_Rhino_Stick-event-joystick -> ../event10
lrwxrwxrwx 1 root root   6 sep.  12 15:59 usb-Mad_Catz_Saitek_Pro_Flight_X-56_Rhino_Stick-joystick -> ../js1
lrwxrwxrwx 1 root root  10 sep.  12 15:59 usb-Mad_Catz_Saitek_Pro_Flight_X-56_Rhino_Throttle-event-joystick -> ../event11
lrwxrwxrwx 1 root root   6 sep.  12 15:59 usb-Mad_Catz_Saitek_Pro_Flight_X-56_Rhino_Throttle-joystick -> ../js2
lrwxrwxrwx 1 root root  10 sep.  12 15:59 usb-Razer_Inc_Razer_Seiren_X_UC1839L01200918-event-if03 -> ../event13
lrwxrwxrwx 1 root root  10 sep.  12 15:59 usb-Razer_Razer_Basilisk-event-if01 -> ../event26
lrwxrwxrwx 1 root root  10 sep.  12 15:59 usb-Razer_Razer_Basilisk-event-mouse -> ../event22
lrwxrwxrwx 1 root root  10 sep.  12 15:59 usb-Razer_Razer_Basilisk-if01-event-kbd -> ../event23
lrwxrwxrwx 1 root root  10 sep.  12 15:59 usb-Razer_Razer_Basilisk-if02-event-kbd -> ../event27
lrwxrwxrwx 1 root root   9 sep.  12 15:59 usb-Razer_Razer_Basilisk-mouse -> ../mouse0
lrwxrwxrwx 1 root root   9 sep.  12 15:59 usb-Razer_Razer_BlackWidow_X_Chroma-event-kbd -> ../event6
lrwxrwxrwx 1 root root   9 sep.  12 15:59 usb-Razer_Razer_BlackWidow_X_Chroma-if01-event-kbd -> ../event8
lrwxrwxrwx 1 root root   9 sep.  12 15:59 usb-Razer_Razer_BlackWidow_X_Chroma-if02-event-mouse -> ../event7
lrwxrwxrwx 1 root root   9 sep.  12 15:59 usb-Razer_Razer_BlackWidow_X_Chroma-if02-mouse -> ../mouse1
lrwxrwxrwx 1 root root   9 sep.  12 15:59 usb-Razer_Razer_Firefly-event-mouse -> ../event3
lrwxrwxrwx 1 root root   9 sep.  12 15:59 usb-Razer_Razer_Firefly-if01-event-kbd -> ../event5
lrwxrwxrwx 1 root root   9 sep.  12 15:59 usb-Razer_Razer_Firefly-if02-event-kbd -> ../event4
lrwxrwxrwx 1 root root   9 sep.  12 15:59 usb-Razer_Razer_Firefly-mouse -> ../mouse2
lrwxrwxrwx 1 root root   9 sep.  12 15:59 usb-Thrustmaster_T-Rudder-event-if00 -> ../event9

```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>

**Comment by z3ntu** [comment] 2019-09-24 09:32
Duplicate of #433

**Closed as completed by z3ntu** 2019-09-24 09:32 UTC
Labels: Device Support
