### ISSUE TITLE
Razer DeathAdder 2013

### ISSUE THREAD

**Issue by hamjo** [openrazer/openrazer#682] opened 2018-09-23 04:14 UTC
I have a Razer DeathAdder, could add support for it?

Here is the output for `lsusb -d 1532: -v`
```
Bus 001 Device 002: ID 1532:0037 Razer USA, Ltd 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0037 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           84
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               8
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      41
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               8
```

And here is the output for `ls -lah /dev/input/by-id/`
```
total 0
drwxr-xr-x 2 root root 180 Sep 22 23:59 .
drwxr-xr-x 4 root root 580 Sep 22 23:59 ..
lrwxrwxrwx 1 root root  10 Sep 22 23:59 usb-151012003121_Lenovo_EasyCamera_200901010001-event-if00 -> ../event14
lrwxrwxrwx 1 root root  10 Sep 22 23:59 usb-Corsair_Corsair_Gaming_K70_LUX_RGB_Keyboard_1802C012AEC584215657BB8DF5001947-event-kbd -> ../event11
lrwxrwxrwx 1 root root  10 Sep 22 23:59 usb-Corsair_Corsair_Gaming_K70_LUX_RGB_Keyboard_1802C012AEC584215657BB8DF5001947-if01-event-kbd -> ../event12
lrwxrwxrwx 1 root root   9 Sep 22 23:59 usb-Razer_Razer_DeathAdder_2013-event-mouse -> ../event8
lrwxrwxrwx 1 root root   9 Sep 22 23:59 usb-Razer_Razer_DeathAdder_2013-if01-event-kbd -> ../event9
lrwxrwxrwx 1 root root  10 Sep 22 23:59 usb-Razer_Razer_DeathAdder_2013-if02-event-kbd -> ../event10
lrwxrwxrwx 1 root root   9 Sep 22 23:59 usb-Razer_Razer_DeathAdder_2013-mouse -> ../mouse1
```

**Comment by z3ntu** [comment] 2018-09-23 12:34
Duplicate of #195

**Closed as completed by z3ntu** 2018-09-23 12:34 UTC
