### ISSUE TITLE
Support for Razer DeathStalker Essential Keyboard

### ISSUE THREAD

**Issue by BahamutGm** [openrazer/openrazer#969] opened 2019-12-10 13:22 UTC
### Device Info

* Name: Razer DeathStalker
* Product Number: RZ03-00800100-R3U1
* Model Number: RZ03-0080

### Device Information
```
Please post the output of lsusb -d 1532:0118 -v

Bus 003 Device 003: ID 1532:0118 Razer USA, Ltd 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0118 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer DeathStalker
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           84
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)
```

```
Please post the output of
    ls -lah /dev/input/by-id/
drwxr-xr-x 2 root root 200 dez 10 09:54 .
drwxr-xr-x 4 root root 540 dez 10 09:54 ..
lrwxrwxrwx 1 root root   9 dez 10 09:54 usb-Razer_Razer_DeathAdder_Essential-event-mouse -> ../event4
lrwxrwxrwx 1 root root   9 dez 10 09:54 usb-Razer_Razer_DeathAdder_Essential-if01-event-kbd -> ../event3
lrwxrwxrwx 1 root root   9 dez 10 09:54 usb-Razer_Razer_DeathAdder_Essential-if02-event-kbd -> ../event6
lrwxrwxrwx 1 root root   9 dez 10 09:54 usb-Razer_Razer_DeathAdder_Essential-mouse -> ../mouse0
lrwxrwxrwx 1 root root   9 dez 10 09:54 usb-Razer_Razer_DeathStalker-event-kbd -> ../event7
lrwxrwxrwx 1 root root   9 dez 10 09:54 usb-Razer_Razer_DeathStalker-if01-event-kbd -> ../event8
lrwxrwxrwx 1 root root   9 dez 10 09:54 usb-Razer_Razer_DeathStalker-if02-event-mouse -> ../event9
lrwxrwxrwx 1 root root   9 dez 10 09:54 usb-Razer_Razer_DeathStalker-if02-mouse -> ../mouse1

```

**Comment by z3ntu** [comment] 2019-12-14 11:55
Duplicate of #368

**Closed as completed by z3ntu** 2019-12-14 11:55 UTC
Labels: Device Support
