### ISSUE TITLE
Support for [Razer Keyboard Cynosa Lite]

### ISSUE THREAD

**Issue by tzehos** [openrazer/openrazer#1101] opened 2020-04-17 13:32 UTC
Can you please add support for the above keyboard because non of razergenie or polychromatic controller recognize the device? Razer Cynosa Chrome is supported but lite not. 

Thank you in advance

**Comment by z3ntu** [comment] 2020-04-19 11:53
Duplicate of #1027, pull request is in #1083

**Closed as completed by z3ntu** 2020-04-19 11:53 UTC
Labels: duplicate, Device Support
