### ISSUE TITLE
Device not popppulating in Razer Genie.

### ISSUE THREAD

**Issue by Shimo** [openrazer/openrazer#889] opened 2019-07-30 06:21 UTC
Device not popppulating in Razer Genie. Getting No device was detected with Razer Naga mouse.

Bus 003 Device 003: ID 1532:002e Razer USA, Ltd RZ01-0058 Gaming Mouse [Naga]

**Comment by z3ntu** [comment] 2019-07-30 13:47
Can you please give me the output of `sudo dkms install openrazer-driver/2.6.0` ?

**Comment by Shimo** [comment] 2019-08-01 07:21
```
sudo dkms install openrazer-driver/2.6.0
Module openrazer-driver/2.6.0 already installed on kernel 4.19.60-1-MANJARO/x86_64
```

Edit: In case you need it too

```
sudo lsusb | grep '1532:'
Bus 003 Device 010: ID 1532:002e Razer USA, Ltd RZ01-0058 Gaming Mouse [Naga]

```

**Comment by z3ntu** [comment] 2019-08-01 09:12
`1532:002e` is not yet supported, if you look into the readme. Closing this as a duplicate of #377

**Closed as completed by z3ntu** 2019-08-01 09:12 UTC
Labels: support
