### ISSUE TITLE
Razer Abyssus Mirror Special Edition Support

### ISSUE THREAD

**Issue by digoburigo** [openrazer/openrazer#759] opened 2019-01-19 14:51 UTC
### Device Info

* Name: Razer Abyssus Mirror Special Edition
* Product Number: RZ01-00360500
* Model Number: RZ01-0036, Optical Gaming Mouse

### Device Information
```
Bus 001 Device 006: ID 1532:001c Razer USA, Ltd RZ01-0036 Optical Gaming Mouse [Abyssus]
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x001c RZ01-0036 Optical Gaming Mouse [Abyssus]
  bcdDevice            1.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           34
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      93
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               8

```

```
total 0
drwxr-xr-x 2 root root 100 Jan 19 12:37 .
drwxr-xr-x 4 root root 560 Jan 19 12:37 ..
lrwxrwxrwx 1 root root  10 Jan 19 12:26 usb-CNFFH36N462410305582_Integrated_Webcam_0x0001-event-if00 -> ../event11
lrwxrwxrwx 1 root root   9 Jan 19 12:37 usb-Razer_Razer_Abyssus-event-mouse -> ../event7
lrwxrwxrwx 1 root root   9 Jan 19 12:37 usb-Razer_Razer_Abyssus-mouse -> ../mouse0
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>

**Comment by z3ntu** [comment] 2019-02-06 16:26
This device seems to be hardware-wise the same as the normal Abyssus (just the case is different), so closing this as a duplicate of #337

**Closed as completed by z3ntu** 2019-02-06 16:26 UTC
Labels: duplicate, Device Support
