### ISSUE TITLE
Mac OS X support for Razor Blackwidow Elite (for lightning)

### ISSUE THREAD

**Issue by michelgokan** [openrazer/openrazer#1048] opened 2020-03-16 08:58 UTC
Is there any plan for supporting Mac?

**Comment by lah7** [comment] 2020-03-16 12:01
Duplicate of #959 (and #991, #1038) but see #959 for details.

Simply put, it's not possible for OpenRazer in its current form to run on Windows/Mac because it depends on a Linux-only driver. There's @z3ntu's razer_test which handles everything in user space, eliminating the need for a driver. It's a work-in-progress, and is already making good progress on Windows/Mac.

Eventually that project will supersede OpenRazer 2.x, so **yes**, it's likely to be supported in future.

**Closed as completed by lah7** 2020-03-16 12:01 UTC
Labels: support
