### ISSUE TITLE
Issue With Openrazer Utility Tools

### ISSUE THREAD

**Issue by Brushtail-Highton** [openrazer/openrazer#509] opened 2018-01-23 21:54 UTC
Both RazerGenie and Polychromatic do not work with a Razer Orochi Gaming Mouse if the mouse is running off Bluetooth in Fedora 27. If the mouse is wired via the usb port the two utilities correctly find the mouse and can perform their work. If the mouse is running off Bluetooth both utilities say that there are no supported devices. The same occurs under Ubuntu 17.10 also.

**Comment by z3ntu** [comment] 2018-01-24 08:53
Duplicate of #346

**Closed as completed by z3ntu** 2018-01-24 08:53 UTC
Labels: invalid
