### ISSUE TITLE
Razer Ornata Chroma V2 | Multimedia Keys

### ISSUE THREAD

**Issue by GivouDev** [openrazer/openrazer#1556] opened 2021-07-11 15:57 UTC
### Distribution

Keyboard: Rater Ornata Chroma V2
Openrazer Version: 3.0.1
Controller: Polychromatic

### Support

- [ X ] Have you tried rebooting?
- [ X ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hello Guys,

i have some toubles to get the multimedia key of the razer ornata chroma v2 working.
When i stop the deamon, everything works fine. I can use my volume wheel and my multimedia keys..but when i start the deamon the multimedia keys(backward, pause/play, forward) write the following (bcd,bcd,bcd) and my volume wheel becomes a mouse wheel.

With FN + F2 or FN + F3 i can change volume up / down.....but there shouldnt be anything.
Is there anyway to stop the deamon from controlling my makros?

Thank you :D

**Comment by sixpounder** [comment] 2021-07-13 16:20
I can confirm this. Stopping the daemon solves the issue, starting it up again brings the issue back.

I investigated a little (got the keyboard today) and seems like the play button, for instance, gets mapped to a combination of three keys (B, C and D to be precise). The volume wheel just falls back to scroll events.

**Comment by z3ntu** [comment] 2021-07-14 06:51
Duplicate of #1398

**Closed as completed by z3ntu** 2021-07-14 06:51 UTC
Labels: support
