### ISSUE TITLE
Support for Razerblade 2018

### ISSUE THREAD

**Issue by kawmaiparis** [openrazer/openrazer#696] opened 2018-10-20 09:42 UTC
In the openrazer web, the Razerblade 2018 is listed as a supported device but it is not listed in the polychromatic daemon log.

**Comment by lah7** [comment] 2018-10-20 20:29
<strike>
It could be possible OpenRazer was improperly installed, so the daemon won't recognise the device. [Have a look at this troubleshooting guide](https://github.com/openrazer/openrazer/wiki/Troubleshooting) in case it's due to missing kernel headers;  or if your user isn't part of the `plugdev` group or if it's because secure boot is enabled.

If none of those troubleshooting suggestions work and you've tried rebooting, let us know what you've tried and your distro.
</strike>

**Comment by lah7** [comment] 2018-10-20 21:14
Oops, turns out the Blade 2018 hasn't hit **stable** yet (thanks for alerting me @z3ntu).

There should be a new release in the next day or two. In the meantime, install the `daily` packages for your distribution if there's one available. In Arch, it's `openrazer-meta-git` or in Ubuntu, the daily PPA:

    sudo add-apt-repository ppa:openrazer/daily
    sudo apt update
    sudo apt install --upgrade openrazer-meta

**Comment by z3ntu** [comment] 2018-10-21 15:48
Duplicate of #605

**Closed as completed by z3ntu** 2018-10-21 15:48 UTC
Labels: support
