### ISSUE TITLE
Support for Razer Abyssus Essential?

### ISSUE THREAD

**Issue by squirreler** [openrazer/openrazer#740] opened 2018-12-20 04:16 UTC
Since the Razer Abyssus, Abyssus V2, and the Abyssus 1800 are supported for open razer could it possibly mean that the Abyssus Essential could also be supported. I doubt that the Abyssus Essential works but I am just wondering

**Comment by z3ntu** [comment] 2018-12-22 16:10
Duplicate of #612

**Closed as completed by z3ntu** 2018-12-22 16:10 UTC
