### ISSUE TITLE
Support for Razer Basilisk Essential

### ISSUE THREAD

**Issue by porresuppe** [openrazer/openrazer#1377] opened 2020-12-19 12:34 UTC
### Device Info

* Name: Razer Basilisk Essential
* Product Number: Rz01-02650100
* Model Number: RZ01-0265

### Device Information
```
Please post the output of
    lsusb -d 1532: -v

Bus 001 Device 006: ID 1532:0065 Razer USA, Ltd
```

```
Please post the output of
    ls -lah /dev/input/by-id/

lrwxrwxrwx 1 root root   9 Dec 19 12:57 usb-Razer_Razer_Basilisk_Essential-event-if01 -> ../event9
lrwxrwxrwx 1 root root   9 Dec 19 12:57 usb-Razer_Razer_Basilisk_Essential-event-mouse -> ../event5
lrwxrwxrwx 1 root root   9 Dec 19 12:57 usb-Razer_Razer_Basilisk_Essential-if01-event-kbd -> ../event6
lrwxrwxrwx 1 root root  10 Dec 19 12:57 usb-Razer_Razer_Basilisk_Essential-if02-event-kbd -> ../event10
lrwxrwxrwx 1 root root   9 Dec 19 12:57 usb-Razer_Razer_Basilisk_Essential-mouse -> ../mouse0

```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

Got stuck at phase 3 (Phase 3 - Reverse Engineering). Couldn't get the colorizer script 

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>

**Comment by z3ntu** [comment] 2020-12-20 13:47
Duplicate of #1134

**Closed as completed by z3ntu** 2020-12-20 13:47 UTC
Labels: duplicate, Device Support
