### ISSUE TITLE
Support for Tartarus Pro

### ISSUE THREAD

**Issue by chiboreache** [openrazer/openrazer#1331] opened 2020-11-12 14:29 UTC
### Device Information

[lsusb.txt](https://github.com/openrazer/openrazer/files/5531197/lsusb.txt)
 

[ls.txt](https://github.com/openrazer/openrazer/files/5531202/ls.txt)

**Comment by z3ntu** [comment] 2020-11-12 14:44
Duplicate of #1039

**Closed as completed by z3ntu** 2020-11-12 14:44 UTC
Labels: duplicate, Device Support
