### ISSUE TITLE
Support for Basilisk V2

### ISSUE THREAD

**Issue by chiboreache** [openrazer/openrazer#1330] opened 2020-11-12 14:25 UTC
[ls.txt](https://github.com/openrazer/openrazer/files/5531208/ls.txt)
[lsusb.txt](https://github.com/openrazer/openrazer/files/5531210/lsusb.txt)

**Comment by z3ntu** [comment] 2020-11-12 14:45
Duplicate of #1078

**Closed as completed by z3ntu** 2020-11-12 14:45 UTC
Labels: duplicate
