### ISSUE TITLE
Razer Blade 15 support

### ISSUE THREAD

**Issue by nakrule** [openrazer/openrazer#695] opened 2018-10-14 17:41 UTC
Would be create to have the new Razer laptop supported.

**Comment by z3ntu** [comment] 2018-10-14 17:46
`lsusb | grep 1532` output please

**Comment by enrapture6** [comment] 2018-10-14 18:59
I got a 2018 razer blade 15 I am trying to running arch on. 

I get lockup crash to an ext4 fs error when waking from lid close suspend/hibernate. Other times boot up and reboot lag or crash/freeze.

I had the same issues when running Ubuntu. I switch to arch as I though controlling all the packages would avoid issues. My conclusion is that the latest kernel does not support the 2018 razer blade 15 hardware yet. 

[enrapture6@razer ~]$ lsusb | grep 1532
Bus 001 Device 004: ID 1532:0233 Razer USA, Ltd 
[enrapture6@razer ~]$

If there are anymore out that one would like to see, let me know.

**Comment by nakrule** [comment] 2018-10-16 16:55
$ lsusb | grep 1532
    Bus 001 Device 004: ID 1532:0233 Razer USA, Ltd 

I have a Razer Blade 2018 running Arch with no issue. Would be great to have the official Razer drivers just to control the keyboard lighting.

**Comment by z3ntu** [comment] 2018-10-18 13:46
Duplicate of #605 (in short: it's already supported, but not yet in a release - which I'll create soon)

**Closed as completed by z3ntu** 2018-10-18 13:46 UTC
Labels: duplicate
