### ISSUE TITLE
Support for BlackWidow Tournament Stealth Edition (2014)

### ISSUE THREAD

**Issue by bartlebee13** [openrazer/openrazer#1295] opened 2020-10-16 15:15 UTC
### Device Info

* Name: BlackWidow Tournament Stealth Edition
* Product Number: RZ03-00811700-R3M1
* Model Number: RZ03-0081

### Device Information
```
Bus 001 Device 006: ID 1532:011c Razer USA, Ltd 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x011c 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               8

Bus 001 Device 004: ID 1532:0037 Razer USA, Ltd USB2.0 Hub             
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0037 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               8
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      41
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               8

```

```
Please post the output of
total 0
drwxr-xr-x 2 root root 240 Oct 16 09:44 .
drwxr-xr-x 4 root root 780 Oct 16 09:44 ..
lrwxrwxrwx 1 root root  10 Oct 16 09:44 usb-Razer_Razer_BlackWidow_Tournament_Edition-event-if01 -> ../event19
lrwxrwxrwx 1 root root  10 Oct 16 09:44 usb-Razer_Razer_BlackWidow_Tournament_Edition-event-kbd -> ../event15
lrwxrwxrwx 1 root root  10 Oct 16 09:44 usb-Razer_Razer_BlackWidow_Tournament_Edition-if01-event-kbd -> ../event16
lrwxrwxrwx 1 root root  10 Oct 16 09:44 usb-Razer_Razer_BlackWidow_Tournament_Edition-if02-event-mouse -> ../event20
lrwxrwxrwx 1 root root   9 Oct 16 09:44 usb-Razer_Razer_BlackWidow_Tournament_Edition-if02-mouse -> ../mouse3
lrwxrwxrwx 1 root root   9 Oct 16 09:44 usb-Razer_Razer_DeathAdder_2013-event-mouse -> ../event7
lrwxrwxrwx 1 root root  10 Oct 16 09:44 usb-Razer_Razer_DeathAdder_2013-if01-event-kbd -> ../event14
lrwxrwxrwx 1 root root  10 Oct 16 09:44 usb-Razer_Razer_DeathAdder_2013-if02-event-kbd -> ../event29
lrwxrwxrwx 1 root root   9 Oct 16 09:44 usb-Razer_Razer_DeathAdder_2013-mouse -> ../mouse0
lrwxrwxrwx 1 root root   9 Oct 16 09:44 usb-Sonix_Technology_Co.__Ltd._BisonCam_NB_Pro-event-if00 -> ../event8

```

### Synapse Screenshots
![Screenshot from 2020-10-16 10-12-28](https://user-images.githubusercontent.com/5341581/96276288-66dae800-0f98-11eb-880f-276aae184795.png)
![Screenshot from 2020-10-16 10-12-39](https://user-images.githubusercontent.com/5341581/96276290-66dae800-0f98-11eb-866c-cb7b980b2d90.png)
![Screenshot from 2020-10-16 10-12-48](https://user-images.githubusercontent.com/5341581/96276292-66dae800-0f98-11eb-876b-2f5696f6e5ad.png)
![Screenshot from 2020-10-16 10-12-55](https://user-images.githubusercontent.com/5341581/96276293-66dae800-0f98-11eb-8228-ed6287b40cb8.png)
![Screenshot from 2020-10-16 10-13-05](https://user-images.githubusercontent.com/5341581/96276294-67737e80-0f98-11eb-953b-37553eaea5e9.png)
![Screenshot from 2020-10-16 10-13-17](https://user-images.githubusercontent.com/5341581/96276296-67737e80-0f98-11eb-821a-8473169a235a.png)
![Screenshot from 2020-10-16 10-13-24](https://user-images.githubusercontent.com/5341581/96276298-67737e80-0f98-11eb-87ad-2b5272556fce.png)

**Comment by z3ntu** [comment] 2020-10-16 19:38
Duplicate of #1050 , if you could test #1194 then we can merge that PR :)

**Closed as completed by z3ntu** 2020-10-16 19:38 UTC
Labels: duplicate, Device Support
