### ISSUE TITLE
Issue with linux kernel 5.5.0

### ISSUE THREAD

**Issue by aFilipMalinowski** [openrazer/openrazer#1014] opened 2020-01-28 09:55 UTC
### Distribution

Operating System: Ubuntu 18.04.3 LTS
Kernel: Linux 5.5.0-050500-generic
Architecture: x86-64
Openrazer: 2.7.0

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hey folks.

After updating kernel to version 5.5, I am getting some errors with openrazer-driver.

Logs attached.
[make.log](https://github.com/openrazer/openrazer/files/4121742/make.log)

**Comment by z3ntu** [comment] 2020-01-28 10:16
Looks like a duplicate of #964 

I think the conclusion of that issue was that mismatching gcc versions were used for compiling the kernel and the kernel module.

**Closed as completed by z3ntu** 2020-01-28 10:16 UTC
Labels: support
