### ISSUE TITLE
Support for Firefly v2

### ISSUE THREAD

**Issue by Sadsurfer** [openrazer/openrazer#1419] opened 2021-01-29 08:44 UTC
### Device Info

* Name: Razer Firefly v2
* Product Number: RZ02-03020100-R3M1
* Model Number: R202-0302

### Device Information

Sorry, on a Mac so not sure if this is right :(
Razer Firefly V2:

  Product ID:	0x0c04
  Vendor ID:	0x1532
  Version:	2.00
  Speed:	Up to 12 Mb/s
  Manufacturer:	RAZER
  Location ID:	0x14311122 / 16
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>

**Comment by z3ntu** [comment] 2021-01-29 08:45
Please use the search function before opening issues, closing as duplicate of #946

**Closed as completed by z3ntu** 2021-01-29 08:45 UTC
Labels: duplicate, Device Support
