### ISSUE TITLE
Manjaro 17.1.6 - Razer DeathAdder Chroma 3500 | Device not recognized

### ISSUE THREAD

**Issue by wmorgue** [openrazer/openrazer#559] opened 2018-03-26 21:56 UTC
My installation (GUI - Polychromatic):
```text
sudo gpasswd -a $USER plugdev

pacaur -a -Qs | grep razer
local/openrazer-daemon 2.2.2-1
local/openrazer-driver-dkms 2.2.2-1
local/openrazer-meta 2.2.2-1
local/python-openrazer 2.2.2-1
```
```text
lsusb | grep '1532:'
Bus 007 Device 002: ID 1532:0016 Razer USA, Ltd DeathAdder Mouse

ls -lah /sys/bus/hid/drivers/
drwxr-xr-x 3 root root 0 мар 27 00:13 .
drwxr-xr-x 4 root root 0 мар 27 00:13 ..
drwxr-xr-x 2 root root 0 мар 27 00:13 hid-generic

ls -lah /sys/bus/hid/drivers/hid-generic/
drwxr-xr-x 2 root root    0 мар 27 00:13 .
drwxr-xr-x 3 root root    0 мар 27 00:13 ..
lrwxrwxrwx 1 root root    0 мар 27 00:21 0003:1532:0016.0003 -> ../../../../devices/pci0000:00/0000:00:13.0/usb7/7-1/7-1:1.0/0003:1532:0016.0003
lrwxrwxrwx 1 root root    0 мар 27 00:21 0003:1C4F:0059.0001 -> ../../../../devices/pci0000:00/0000:00:07.0/0000:02:00.0/usb2/2-2/2-2:1.0/0003:1C4F:0059.0001
lrwxrwxrwx 1 root root    0 мар 27 00:21 0003:1C4F:0059.0002 -> ../../../../devices/pci0000:00/0000:00:07.0/0000:02:00.0/usb2/2-2/2-2:1.1/0003:1C4F:0059.0002
--w------- 1 root root 4,0K мар 27 00:21 bind
lrwxrwxrwx 1 root root    0 мар 27 00:21 module -> ../../../../module/hid_generic
--w------- 1 root root 4,0K мар 27 00:21 new_id
--w------- 1 root root 4,0K мар 27 00:21 uevent
--w------- 1 root root 4,0K мар 27 00:21 unbind
```
```text
sudo dkms install openrazer-driver/1.0.0; sudo dkms status

Module openrazer-driver/1.0.0 already installed on kernel 4.14.29-1-MANJARO/x86_64
openrazer-driver, 1.0.0, 4.14.29-1-MANJARO, x86_64: installed
```
```text
python3 -c "from openrazer.client import DeviceManager; a = DeviceManager(); print(a.devices)"
[]
```
```text
systemctl --user status openrazer-daemon.service

● openrazer-daemon.service - Daemon to manage razer devices in userspace
   Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-03-27 00:42:06 MSK; 44s ago
     Docs: man:openrazer-daemon(8)
 Main PID: 3123 (openrazer-daemo)
   CGroup: /user.slice/user-1000.slice/user@1000.service/openrazer-daemon.service
           └─3123 openrazer-daemon

мар 27 00:42:06 dima openrazer-daemon[3123]: 2018-03-27 00:42:06 | razer                          | DEBUG    | Adding razer.devices.enableTurnOffOnScreensaver method to DBus
мар 27 00:42:06 dima openrazer-daemon[3123]: 2018-03-27 00:42:06 | razer                          | DEBUG    | Adding razer.devices.getOffOnScreensaver method to DBus
мар 27 00:42:06 dima openrazer-daemon[3123]: 2018-03-27 00:42:06 | razer                          | DEBUG    | Adding razer.daemon.version method to DBus
мар 27 00:42:06 dima openrazer-daemon[3123]: 2018-03-27 00:42:06 | razer                          | DEBUG    | Adding razer.devices.supportedDevices method to DBus
мар 27 00:42:06 dima openrazer-daemon[3123]: 2018-03-27 00:42:06 | razer                          | DEBUG    | Adding razer.devices.getDevices method to DBus
мар 27 00:42:06 dima openrazer-daemon[3123]: 2018-03-27 00:42:06 | razer                          | DEBUG    | Adding razer.devices.syncEffects method to DBus
мар 27 00:42:06 dima openrazer-daemon[3123]: 2018-03-27 00:42:06 | razer                          | DEBUG    | Adding razer.devices.getSyncEffects method to DBus
мар 27 00:42:06 dima openrazer-daemon[3123]: 2018-03-27 00:42:06 | razer                          | DEBUG    | Adding razer.daemon.stop method to DBus
мар 27 00:42:06 dima openrazer-daemon[3123]: 2018-03-27 00:42:06 | razer                          | INFO     | Serving DBus
мар 27 00:42:06 dima openrazer-daemon[3123]: 2018-03-27 00:42:06 | razer                          | DEBUG    | DBus called get_serial_list
```
```text
lsmod | grep razer
razerkbd               69632  0
hid                   131072  3 hid_generic,usbhid,razerkbd
usbcore               282624  8 usbhid,razerkbd,ehci_hcd,ohci_pci,xhci_pci,ohci_hcd,xhci_hcd,ehci_pci

ls -al /sys/bus/hid/drivers/razermouse/0*/
zsh: no matches found: /sys/bus/hid/drivers/razermouse/0*/
```
[openrazer-daemon -Fv](https://gist.github.com/BORN2LOSE/15ea2ac9cf3accea8d4e05d15381558e)
[lsusb -d 1532:0016 -v](https://gist.github.com/BORN2LOSE/a8bb15e6bc9158558ad773f0e679c33e)

cc @z3ntu

**Comment by z3ntu** [comment] 2018-03-27 08:35
That device is not yet supported. Duplicate of #231

**Closed as completed by z3ntu** 2018-03-27 08:35 UTC
