### ISSUE TITLE
Razer Cynosa Pro Support

### ISSUE THREAD

**Issue by nathen148** [openrazer/openrazer#1000] opened 2020-01-19 02:54 UTC
Im wondering how i can get openrazer to work with the Cynosa Pro they are not really that different between the pro and non pro version the only real difference is the underglow could you by chance add support for this keyboard?

**Comment by z3ntu** [comment] 2020-02-08 13:46
Duplicate of #811

**Closed as completed by z3ntu** 2020-02-08 13:46 UTC
