### ISSUE TITLE
Support for Laptop Stand Chroma

### ISSUE THREAD

**Issue by Sadsurfer** [openrazer/openrazer#1420] opened 2021-01-29 08:45 UTC
### Device Info

* Name: Razer Laptop Stand Chroma
* Product Number:RC21-01110200-R3M1
* Model Number: 

### Device Information
```
On a Mac so not sure if this is right or helps
Razer Laptop Stand Chroma:

  Product ID:	0x0f0d
  Vendor ID:	0x1532
  Version:	2.00
  Speed:	Up to 12 Mb/s
  Manufacturer:	Razer
  Location ID:	0x14311114 / 13
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0
```

```
Please post the output of
    ls -lah /dev/input/by-id/
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>

**Comment by z3ntu** [comment] 2021-01-29 08:47
Duplicate of #866

**Closed as completed** 2021-01-29 08:47 UTC
Labels: duplicate, Device Support
