### ISSUE TITLE
Support for LIAN LI O11 DYNAMIC – DESIGNED BY RAZER

### ISSUE THREAD

**Issue by edgarsilva** [openrazer/openrazer#961] opened 2019-12-02 21:05 UTC
This seems to be just a razer chroma RGB led strip, I'm happy to provide all info and debug test/time. I'm also a developer with many years of experience, unfortunately I haven't done much C programming in a long time. But I can also contribute with code testing if needed. Thanks.

PS: I'll include the Razer Synapse Screenshots as soon as I log into windows.

### Device Info
* Name: LIAN LI O11 DYNAMIC – DESIGNED BY RAZER
* Product Number: 
* Model Number: 011DXRZ

### Device Information
```
Please post the output of
    $ sudo lsusb -d 1532: -v

Bus 003 Device 005: ID 1532:0f13 Razer USA, Ltd 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0f13 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Lian Li O11 Dynamic Designed by Razer
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)
```

```
Please post the output of
    $ ls -lah /dev/input/by-id/
total 0
drwxr-xr-x 2 root root 300 Dec  2 13:51 .
drwxr-xr-x 4 root root 680 Dec  2 13:51 ..
lrwxrwxrwx 1 root root   9 Dec  2 11:41 usb-Razer_Lian_Li_O11_Dynamic_Designed_by_Razer-event-if01 -> ../event6
lrwxrwxrwx 1 root root   9 Dec  2 11:41 usb-Razer_Lian_Li_O11_Dynamic_Designed_by_Razer-event-kbd -> ../event2
lrwxrwxrwx 1 root root   9 Dec  2 11:41 usb-Razer_Lian_Li_O11_Dynamic_Designed_by_Razer-if01-event-kbd -> ../event3
lrwxrwxrwx 1 root root  10 Dec  2 11:41 usb-Razer_Lian_Li_O11_Dynamic_Designed_by_Razer-if02-event-mouse -> ../event11
lrwxrwxrwx 1 root root   9 Dec  2 11:41 usb-Razer_Lian_Li_O11_Dynamic_Designed_by_Razer-if02-mouse -> ../mouse1
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>

**Comment by z3ntu** [comment] 2019-12-15 16:14
Duplicate of #903

**Closed as completed by z3ntu** 2019-12-15 16:14 UTC
Labels: Device Support
