### ISSUE TITLE
Device Support for Razer ManO'War

### ISSUE THREAD

**Issue by simongoertzen** [openrazer/openrazer#492] opened 2018-01-03 15:56 UTC
The headset works for me, but the volume wheel (up/down/mute) does not.

[lsusb.txt](https://github.com/openrazer/openrazer/files/1600860/lsusb.txt)
[by-id.txt](https://github.com/openrazer/openrazer/files/1600859/by-id.txt)
![polychromatic](https://user-images.githubusercontent.com/23029327/34527603-5489eb74-f0a6-11e7-835d-5371608f0aca.png)

**Comment by z3ntu** [comment] 2018-01-04 12:29
Please search for existing issues before opening new ones. Duplicate of #43

**Closed as completed by z3ntu** 2018-01-04 12:29 UTC
