### ISSUE TITLE
naga trinity 1532:0067

### ISSUE THREAD

**Issue by pitaluke** [openrazer/openrazer#921] opened 2019-10-03 02:12 UTC
### Device Info

* Name: naga trinity
* Product Number: <See under device>
* Model Number: <See under device>

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```Bus 001 Device 010: ID 1532:0067 Razer USA, Ltd 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0067 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 3 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1


```
Please post the output of
    ls -lah /dev/input/by-id/
```
total 0
drwxr-xr-x 2 root root 400 Oct  2 21:00 .
drwxr-xr-x 4 root root 880 Oct  2 21:00 ..
lrwxrwxrwx 1 root root  10 Oct  2 20:55 usb-Blue_Microphones_Yeti_Stereo_Microphone_FST_2018_06_13_59459-event-if03 -> ../event22
lrwxrwxrwx 1 root root   9 Oct  2 20:55 usb-Kingston_HyperX_7.1_Audio_00000000-event-if03 -> ../event9
lrwxrwxrwx 1 root root  10 Oct  2 20:55 usb-Kingston_HyperX_Cloud_Flight_Wireless_Headset-event-if03 -> ../event12
lrwxrwxrwx 1 root root  10 Oct  2 21:00 usb-Razer_Razer_BlackWidow_Elite-event-kbd -> ../event24
lrwxrwxrwx 1 root root  11 Oct  2 21:00 usb-Razer_Razer_BlackWidow_Elite-if01-event-kbd -> ../event258
lrwxrwxrwx 1 root root   9 Oct  2 21:00 usb-Razer_Razer_BlackWidow_Elite-if02-event-mouse -> ../event8
lrwxrwxrwx 1 root root   9 Oct  2 21:00 usb-Razer_Razer_BlackWidow_Elite-if02-mouse -> ../mouse0
lrwxrwxrwx 1 root root  10 Oct  2 21:00 usb-Razer_Razer_Firefly-event-mouse -> ../event23
lrwxrwxrwx 1 root root   9 Oct  2 21:00 usb-Razer_Razer_Firefly-if01-event-kbd -> ../event5
lrwxrwxrwx 1 root root  10 Oct  2 21:00 usb-Razer_Razer_Firefly-if02-event-kbd -> ../event28
lrwxrwxrwx 1 root root   9 Oct  2 21:00 usb-Razer_Razer_Firefly-mouse -> ../mouse3
lrwxrwxrwx 1 root root  10 Oct  2 20:55 usb-Razer_Razer_Naga_Trinity_00000000001A-event-if01 -> ../event18
lrwxrwxrwx 1 root root  10 Oct  2 20:55 usb-Razer_Razer_Naga_Trinity_00000000001A-event-mouse -> ../event16
lrwxrwxrwx 1 root root  10 Oct  2 20:55 usb-Razer_Razer_Naga_Trinity_00000000001A-if01-event-kbd -> ../event17
lrwxrwxrwx 1 root root  10 Oct  2 20:55 usb-Razer_Razer_Naga_Trinity_00000000001A-if02-event-kbd -> ../event21
lrwxrwxrwx 1 root root   9 Oct  2 20:55 usb-Razer_Razer_Naga_Trinity_00000000001A-mouse -> ../mouse2
lrwxrwxrwx 1 root root  10 Oct  2 20:55 usb-Valve_Software_Steam_Controller-event-mouse -> ../event15
lrwxrwxrwx 1 root root   9 Oct  2 20:55 usb-Valve_Software_Steam_Controller-mouse -> ../mouse1

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>

**Comment by z3ntu** [comment] 2019-10-03 06:15
Duplicate of #541

**Closed as completed by z3ntu** 2019-10-03 06:15 UTC
Labels: Device Support
