### ISSUE TITLE
openrazer-daemon fails to start; "org.freedesktop.DBus.Error.ServiceUnknown"

### ISSUE THREAD

**Issue by thunderrd** [openrazer/openrazer#431] opened 2017-11-05 06:08 UTC
Using the app-misc/openrazer package from vifino's Gentoo overlay, along with polychromatic, I get this message when starting polychromatic:

"org.freedesktop.DBus.Error.ServiceUnknown: The name :1.48 was not provided by any .service files"

And when using a terminal:
```
thunderrd@Q6600:~$ openrazer-daemon -Fv
2017-11-01 21:44:38 | razer                          | INFO     | Initialising Daemon (v2.0.0). Pid: 13092
2017-11-01 21:44:38 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerAbyssusV2 -------------------------- (1532:005B)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerAnansi ----------------------------- (1532:010F)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaOverwatch ---------- (1532:0211)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaV2 ----------------- (1532:0221)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: 

2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassic ------------------ (1532:011B)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassicAlternate --------- (1532:010E)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2012 ------------- (1532:010D)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2013 ------------- (1532:011A)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2016 ------------- (1532:0214)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXTournamentEditionChroma - (1532:021A)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXUltimate ---------------- (1532:0217)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBladeLate2016 ---------------------- (1532:0224)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017 ----------------------- (1532:0225)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBladeProLate2016 ------------------- (1532:0210)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBladeQHD --------------------------- (1532:020F)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth ----------------------- (1532:0205)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2016 --------------- (1532:0220)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2017 --------------- (1532:0232)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthMid2017 ---------------- (1532:022D)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerChromaMugHolder -------------------- (1532:0F07)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerCore ------------------------------- (1532:0215)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderChroma ------------------- (1532:0043)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderElite -------------------- (1532:005C)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerChroma ----------------- (1532:0204)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerExpert ----------------- (1532:0202)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerDiamondbackChroma ------------------ (1532:004C)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerFirefly ---------------------------- (1532:0C00)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerImperator -------------------------- (1532:002F)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerKraken ----------------------------- (1532:0504)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerKrakenClassic ---------------------- (1532:0501)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerKrakenV2 --------------------------- (1532:0510)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wired --------------------- (1532:0024)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wireless ------------------ (1532:0025)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWired ------------------- (1532:0044)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWireless ---------------- (1532:0045)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerMambaTE ---------------------------- (1532:0046)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerNaga2014 --------------------------- (1532:0040)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerNagaChroma ------------------------- (1532:0053)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerNagaHex ---------------------------- (1532:0041)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexRed ------------------------- (1532:0036)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerNostromo --------------------------- (1532:0111)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaver -------------------------- (1532:0113)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaverChroma -------------------- (1532:0207)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerOrnata ----------------------------- (1532:021F)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2011 ------------------------- (1532:0013)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2013 ------------------------- (1532:0039)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerOuroboros -------------------------- (1532:0032)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerTaipan ----------------------------- (1532:0034)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0201)
2017-11-01 21:44:38 | razer                          | DEBUG    | Loaded device specification: RazerTartarusChroma --------------------- (1532:0208)
2017-11-01 21:44:38 | razer                          | INFO     | Found device.0: 0003:1532:0214.0003
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/openrazer_daemon/hardware/device_base.py", line 421, in __del__
    self.close()
  File "/usr/lib64/python3.6/site-packages/openrazer_daemon/hardware/device_base.py", line 334, in close
    if not self._is_closed:
AttributeError: 'RazerBlackWidowUltimate2016' object has no attribute '_is_closed'
thunderrd@Q6600:~$
```

It appears the daemon is not starting at all, and exiting with the above message.  Any advice on how to troubleshoot this?

**Comment by z3ntu** [comment] 2017-11-05 10:10
Can you please try applying the following patch to the file `/usr/lib/python3.6/site-packages/openrazer_daemon/hardware/device_base.py` and restarting the daemon?

```
diff --git a/daemon/openrazer_daemon/hardware/device_base.py b/daemon/openrazer_daemon/hardware/device_base.py
index f6acf70..1771229 100644
--- a/daemon/openrazer_daemon/hardware/device_base.py
+++ b/daemon/openrazer_daemon/hardware/device_base.py
@@ -331,10 +331,13 @@ class RazerDevice(DBusService):
         """
         Close any resources opened by subclasses
         """
-        if not self._is_closed:
-            self._close()
+        try:
+            if not self._is_closed:
+                self._close()
 
-            self._is_closed = True
+                self._is_closed = True
+        except AttributeError:
+            self.logger.info("_is_closed doesn't exist. Ignoring.")
 
     def register_observer(self, observer):
```

**Comment by thunderrd** [comment] 2017-11-05 12:46
After patching:

``
thunderrd@Q6600:~$ openrazer-daemon -Fv
2017-11-05 19:43:30 | razer                          | INFO     | Initialising Daemon (v2.0.0). Pid: 4542
2017-11-05 19:43:30 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor

thunderrd@Q6600:~$
``

Looks like a pid was created, but there is no matching pid in htop afterwards

**Comment by z3ntu** [comment] 2017-11-05 12:52
That doesn't make any sense... It seems that stderr isn't being printed with `openrazer-daemon -Fv`...

**Comment by thunderrd** [comment] 2017-11-05 12:57
Is there no debug flag/switch?

**Comment by z3ntu** [comment] 2017-11-05 13:00
What distro are you using? I checked and there was a regression after commit 8219aa7826e1bc909f07366086653069f36133ea (most likely introduced with the python-daemonize merge...)

**Comment by thunderrd** [comment] 2017-11-05 13:04
Using Gentoo, and the openrazer/polychromatic packages from here:
https://github.com/vifino/vifino-overlay/tree/master/app-misc

I reported this to the overlay maintainer first, and he directed me upstream.

**Comment by z3ntu** [comment] 2017-11-05 13:24
Is it possible to specify a git revision in an ebuild? If yes, please use 8219aa7826e1bc909f07366086653069f36133ea and install it from that revision.

**Comment by z3ntu** [comment] 2017-11-05 13:25
@whot It seems that stderr isn't outputted by python-daemonize. Do you know a way to not just get stdout?

**Comment by whot** [comment] 2017-11-06 01:30
See PR #432 for a quickfix, I've also filed https://github.com/thesharp/daemonize/issues/65

**Comment by jkmac0** [comment] 2017-11-06 07:56
I am also on gentoo but using python3.5. Just upgrading to openrazer from razer-drivers. The bug appears to affect the keyboard RazerBlackWidowUltimate2016 only, if I unplug it the daemon will start with my Taipan. With it plugged in I get the same error as above, after patching device_base.py I get the output below.

```

2017-11-06 07:51:41 | razer                          | INFO     | Initialising Daemon (v2.0.0). Pid: 2589
2017-11-06 07:51:41 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerAbyssusV2 -------------------------- (1532:005B)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerAnansi ----------------------------- (1532:010F)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaOverwatch ---------- (1532:0211)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaV2 ----------------- (1532:0221)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassic ------------------ (1532:011B)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassicAlternate --------- (1532:010E)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2012 ------------- (1532:010D)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2013 ------------- (1532:011A)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2016 ------------- (1532:0214)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXTournamentEditionChroma - (1532:021A)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXUltimate ---------------- (1532:0217)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBladeLate2016 ---------------------- (1532:0224)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017 ----------------------- (1532:0225)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBladeProLate2016 ------------------- (1532:0210)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBladeQHD --------------------------- (1532:020F)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth ----------------------- (1532:0205)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2016 --------------- (1532:0220)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2017 --------------- (1532:0232)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthMid2017 ---------------- (1532:022D)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerChromaMugHolder -------------------- (1532:0F07)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerCore ------------------------------- (1532:0215)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderChroma ------------------- (1532:0043)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderElite -------------------- (1532:005C)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerChroma ----------------- (1532:0204)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerExpert ----------------- (1532:0202)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerDiamondbackChroma ------------------ (1532:004C)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerFirefly ---------------------------- (1532:0C00)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerImperator -------------------------- (1532:002F)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerKraken ----------------------------- (1532:0504)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerKrakenClassic ---------------------- (1532:0501)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerKrakenV2 --------------------------- (1532:0510)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wired --------------------- (1532:0024)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wireless ------------------ (1532:0025)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWired ------------------- (1532:0044)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWireless ---------------- (1532:0045)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerMambaTE ---------------------------- (1532:0046)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerNaga2014 --------------------------- (1532:0040)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerNagaChroma ------------------------- (1532:0053)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerNagaHex ---------------------------- (1532:0041)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexRed ------------------------- (1532:0036)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerNostromo --------------------------- (1532:0111)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaver -------------------------- (1532:0113)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaverChroma -------------------- (1532:0207)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerOrnata ----------------------------- (1532:021F)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2011 ------------------------- (1532:0013)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2013 ------------------------- (1532:0039)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerOuroboros -------------------------- (1532:0032)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerTaipan ----------------------------- (1532:0034)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0201)
2017-11-06 07:51:41 | razer                          | DEBUG    | Loaded device specification: RazerTartarusChroma --------------------- (1532:0208)
2017-11-06 07:51:41 | razer                          | INFO     | Found device.0: 0003:1532:0034.000C
2017-11-06 07:51:41 | razer.device0                  | INFO     | Initialising device.0 RazerTaipan
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.getSerial method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDriverVersion method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.suspendDevice method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.setDeviceMode method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.getVidPid method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasDedicatedMacroKeys method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceMode method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.resumeDevice method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.getRazerUrls method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.getFirmware method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.getMatrixDimensions method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasMatrix method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceName method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceType method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.dpi.maxDPI method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.dpi.getDPI method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.dpi.setDPI method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.getPollRate method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.misc.setPollRate method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.getLogoActive method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoActive method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.getScrollActive method to DBus
2017-11-06 07:51:41 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollActive method to DBus
2017-11-06 07:51:41 | razer                          | INFO     | Found device.1: 0003:1532:0214.0013
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/openrazer_daemon/hardware/device_base.py", line 424, in __del__
    self.close()
  File "/usr/lib64/python3.5/site-packages/openrazer_daemon/hardware/device_base.py", line 340, in close
    self.logger.info("_is_closed doesn't exist. Ignoring.")
AttributeError: 'RazerBlackWidowUltimate2016' object has no attribute 'logger'

```
output from systemd log
```

Nov 06 08:08:15 megan openrazer-daemon[1342]: Starting daemon.
Nov 06 08:08:15 megan openrazer-daemon[1342]: Traceback (most recent call last):
Nov 06 08:08:15 megan openrazer-daemon[1342]:   File "/usr/lib64/python3.5/site-packages/daemonize.py", line 245, in start
Nov 06 08:08:15 megan openrazer-daemon[1342]:     self.action(*privileged_action_result)
Nov 06 08:08:15 megan openrazer-daemon[1342]:   File "/usr/bin/openrazer-daemon", line 121, in run_daemon
Nov 06 08:08:15 megan openrazer-daemon[1342]:     test_dir=args.test_dir)
Nov 06 08:08:15 megan openrazer-daemon[1342]:   File "/usr/lib64/python3.5/site-packages/openrazer_daemon/daemon.py", line 106, in __init__
Nov 06 08:08:15 megan openrazer-daemon[1342]:     self._load_devices(first_run=True)
Nov 06 08:08:15 megan openrazer-daemon[1342]:   File "/usr/lib64/python3.5/site-packages/openrazer_daemon/daemon.py", line 401, in _load_devices
Nov 06 08:08:15 megan openrazer-daemon[1342]:     razer_device = device_class(sys_path, device_number, self._config, testing=self._test_dir is not None, additional_interfaces=sorted(additional_interfaces))
Nov 06 08:08:15 megan openrazer-daemon[1342]:   File "/usr/lib64/python3.5/site-packages/openrazer_daemon/hardware/keyboards.py", line 702, in __init__
Nov 06 08:08:15 megan openrazer-daemon[1342]:     super(RazerBlackWidow2016, self).__init__(*args, **kwargs)
Nov 06 08:08:15 megan openrazer-daemon[1342]: NameError: name 'RazerBlackWidow2016' is not defined
Nov 06 08:08:15 megan openrazer-daemon[1342]: 
Nov 06 08:08:15 megan openrazer-daemon[1342]: Stopping daemon.

```

**Comment by thunderrd** [comment] 2017-11-06 08:10
Yeah, that's similar to my OP, with the same KB, but I'm not sure if that's a coincidence or if it's significant.

However, I patched the file as well, and do not get the DEBUG output you have there.

**Comment by jkmac0** [comment] 2017-11-06 08:34
Try changing lines 702 & 710 in /usr/lib/python3.x/site-packages/openrazer_daemon/hardware/keyboards.py 

```
--- a/keyboards.py      2017-11-06 08:54:09.215127462 +0000
+++ b/keyboards.py      2017-11-06 08:59:13.742796963 +0000
@@ -699,7 +699,7 @@
     }
 
     def __init__(self, *args, **kwargs):
-        super(RazerBlackWidow2016, self).__init__(*args, **kwargs)
+        super(RazerBlackWidowUltimate2016, self).__init__(*args, **kwargs)
 
         self.ripple_manager = _RippleManager(self, self._device_number)
 
@@ -707,7 +707,7 @@
         """
         Close the key manager
         """
-        super(RazerBlackWidow2016, self)._close()
+        super(RazerBlackWidowUltimate2016, self)._close()
 
         self.ripple_manager.close()

```


works for me

**Comment by z3ntu** [comment] 2017-11-06 09:03
Fixed in https://github.com/openrazer/openrazer/commit/552cb204101181c2a2a1db1e49137d9cf725c54b, sorry for breaking it.

**Closed as completed** 2017-11-09 18:43 UTC
Labels: bug
