### ISSUE TITLE
Is Naga Molten Supported?

### ISSUE THREAD

**Issue by EdWata** [openrazer/openrazer#1324] opened 2020-11-05 18:52 UTC
Hello,

I have a Razer Naga Molten Edition with ID 1532:0015. I saw that Razer Naga 2012 is supported and i wonder if there is any way to make it work with mine since they are way too alike. I'm working on Ubuntu 16.04 LTS and i need to bind some keys and lower the DPI.
Thanks for your time, i hope not to bother you.

**Comment by z3ntu** [comment] 2020-11-06 08:38
Duplicate of #139

> bind some keys

This is currently not supported in openrazer, #1124 does something like that but not for mice as far as I know.

> lower the DPI.

That will be supported when support is added.

**Closed as completed by z3ntu** 2020-11-06 08:38 UTC
Labels: duplicate
