### ISSUE TITLE
Request support for Razor BlackWindow Elite on Fedora

### ISSUE THREAD

**Issue by kunjanrathod11** [openrazer/openrazer#731] opened 2018-12-10 06:20 UTC
Currently Razor BlackWindow Elite is not supported. 

getting the keyboard is not listed when seen in logs:
~~~
openrazer-daemon -Fv
Starting daemon.
2018-12-10 17:11:17 | razer                          | INFO     | Initialising Daemon (v2.4.0). Pid: 32229
2018-12-10 17:11:17 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus1800 ------------------------ (1532:0020)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerAbyssusV2 -------------------------- (1532:005B)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerAnansi ----------------------------- (1532:010F)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaOverwatch ---------- (1532:0211)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaV2 ----------------- (1532:0221)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowStealth ------------------ (1532:011B)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowStealthEdition ----------- (1532:010E)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2012 ------------- (1532:010D)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2013 ------------- (1532:011A)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2016 ------------- (1532:0214)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXTournamentEditionChroma - (1532:021A)
2018-12-10 17:11:17 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXUltimate ---------------- (1532:0217)
...
~~~

Also,  Polychromatic Controller does gives the message that it does not recognise any device.

I have installed openrazer-daemon 2.4.0.

The keyboard unfortunately does not have any inbuilt patterns that can be changed on the fly without relying on the software.

**Comment by z3ntu** [comment] 2018-12-10 06:32
Duplicate of #684

**Closed as completed by z3ntu** 2018-12-10 06:32 UTC
